#!/usr/bin/env php
<?php

/*
 * This file is part of the Insulin CLI
 *
 * Copyright (c) 2008-2012 Filipe Guerra, João Morais
 * http://cli.sugarmeetsinsulin.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

set_time_limit(0);

require_once __DIR__.'/autoload.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$debug = $input->hasParameterOption(array('--debug', '-d'));

$kernel = new \Insulin\Console\Kernel($debug);
$application = new Insulin\Console\Application($kernel);
$application->run($input);
